version: "3.7"
services:
  rule-manager:
    build: ./rule-manager
    container_name: rule-manager
    depends_on:
      -  cache
    ports:
      - 9000:8080 
  server:
    build: ./server 
    container_name: nginx-base
    ports:
      - 80:80
  cache:
    image: redis:6.2-alpine
    container_name: redis_cache
    restart: always
    ports:
      - '6300:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
